Adds Groth16
arkworks-rs/snark pull request #37
Opened 2019-10-20 18:01 UTC by kobigurk

2019-10-20 23:09 UTC, Pratyush requested changes
Thanks for the PR, it looks great! Just a couple of additional comments:
- [x] Instead of adding the LICENSE files directly, could you instead make them symlinks like in the other crates?
- [x] Could you run the crate through `cargo fmt`? I noticed a couple of inconsistent indentation things.

2019-10-20 23:09 UTC, Pratyush commented on crypto-primitives/src/nizk/groth16/mod.rs
> +        let verify_time = start_timer!(|| "{Groth-Maller 2017}::Verify");
```suggestion
        let verify_time = start_timer!(|| "{Groth 2016}::Verify");
```

2019-10-20 23:09 UTC, Pratyush commented on crypto-primitives/src/nizk/groth16/mod.rs
> +        let proof_time = start_timer!(|| "{Groth-Maller 2017}::Prove");
```suggestion
        let proof_time = start_timer!(|| "{Groth 2016}::Prove");
```

2019-10-20 23:09 UTC, Pratyush commented on crypto-primitives/src/nizk/groth16/mod.rs
> +        let nizk_time = start_timer!(|| "{Groth-Maller 2017}::Setup");
```suggestion
        let nizk_time = start_timer!(|| "{Groth 2016}::Setup");
```

2019-10-20 23:09 UTC, Pratyush commented on groth16/src/lib.rs
> +//! An implementation of the [Groth][Groth16] simulation extractable zkSNARK.
```suggestion
//! An implementation of the [Groth][Groth16] zkSNARK.
```

2019-10-20 23:09 UTC, Pratyush commented on groth16/src/generator.rs
> +    &l,
```suggestion
        &l,
```

2019-10-21 11:22 UTC, kobigurk commented
All done!

I noticed that `cargo fmt` with the latest nightly did more changes than I expected. Do you have a particular config you're using?

If not, we should run the whole Zexe workspace through it.

2019-10-21 17:57 UTC, Pratyush commented
I think it should use the rustfmt.toml that's in the repository root. From looking at the fmt commit, it seems that it used this config.

I usually run it on every crate except algebra because the formatting on constants gets screwed up by rustfmt.

2019-10-21 20:26 UTC, kobigurk commented
Got it. I think we can leave the formatting to another PR so this wouldn't affect the whole repository?

2019-10-21 20:34 UTC, Pratyush commented
Sure, as you wish!

2019-10-22 01:57 UTC, merged

2019-10-22 02:02 UTC, Pratyush commented
Thanks for the PR @kobigurk! It's great to have another implementation of Groth16 in Rust =)