r1cs replaced with gr1cs
arkworks-rs/snark pull request #378
Opened 2024-08-06 21:40 UTC by alireza-shirzad

## Description

This is a major refactor for migrating to GR1CS infrastructure

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2024-08-07 21:27 UTC, Pratyush reviewed
Some changes

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +/// An Rank-One `ConstraintSystem`. Enforces constraints of the form
```suggestion
/// A Rank-1 `ConstraintSystem`. Enforces constraints of the form
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +/// `z` is the concrete assignment to these variables. refer to //TODO: Paper Url
Fix url

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        // if self.should_construct_matrices() {
todo fix tracing

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        lc_vec: Vec<LinearCombination<F>>,
```suggestion
        lc_vec: impl IntoIterator<Item = LinearCombination<F>>,
```

I can pass in `[lc_1, lc_2, lc_3]`, or I can pass in `vec![lc_1, lc_2, lc_3]`. The benefit is that this avoids allocations

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        }
```suggestion
        let constraints: Vec<_> = lc_vec.into_iter().map(|lc| {
            let var = self.new_lc(lc)?;
            match var {
                Variable::SymbolicLc(index) => constraints.push(index),
                _ => return Err(SynthesisError::UnexpectedVariable),
            }
        }).collect();
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        }
I would not do this, as it makes the constraint synthesis quadratic in the number of LCs. If you want deduplication, you can use something like [`bimap`](https://docs.rs/bimap/latest/bimap/)

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +                            .as_ref()
```suggestion
                            .predicate_traces[&label][unsatisfied_constraint]
                            .as_ref()
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +                                |t| format!("{}", t),
```suggestion
                                    format!("{} - {unsatisfied_constraint}", &label)
                                },
                                |t| format!("{t}"),
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/local_predicate/mod.rs
> +// use crate::{gr1cs::ConstraintSystemRef, utils::Result};
```suggestion
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/local_predicate/mod.rs
> +    LookupConstraint<F>: Evaluatable<F>,
```suggestion
```

2024-08-07 21:27 UTC, Pratyush commented on relations/src/gr1cs/local_predicate/mod.rs
> +}
Add documentation for trait, and change `point` to variables

2025-01-16 21:53 UTC, Pratyush requested changes
Thanks for PR!

2025-01-16 21:53 UTC, Pratyush commented on relations/examples/Non-Satisfiable.rs
> +
rename this file to lower-case

2025-01-16 21:53 UTC, Pratyush commented on relations/examples/README.MD
> +cargo run --example non-satisfiable --features std
```suggestion
cargo run --example non-satisfiable --features std
# add closing block
```

2025-01-16 21:53 UTC, Pratyush commented on relations/examples/Satisfiable.rs
> +use ark_ff::Field;
rename this to lowercase

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +//! each of which enforce have seperate predicates and constraints. For more infomation about the terminology and the structure of the constraint system, refer to https://eprint.iacr.org/2024/1245
Maybe add a specific section in the paper?
```suggestion
//! each of which enforce have seperate predicates and constraints. 
//! For more infomation about the terminology and the structure of the constraint system, refer to https://eprint.iacr.org/2024/1245.
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    cache_map: Rc<RefCell<BTreeMap<TypeId, Box<dyn Any>>>>,
```suggestion
    pub cache_map: Rc<RefCell<BTreeMap<TypeId, Box<dyn Any>>>>,
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    /// Note that no predicate is registered yet
```suggestion
    /// Note that by default, the constraint system is 
    /// registered with the R1CS predicate.
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    /// Returns the number of constraints in each predicate
Change the comment to say that it returns a mapping from predicate label to number of constraints for that predicate.

Maybe we should also add a function `get_num_constraints_for_pred` which takes as input a label and returns the number of constraints for that.

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        types
```suggestion
        self.predicate_constraint_systems.iter().map(|(label, predicate_cs))| (label.to_string(), predicate_cs.get_predicate_type())).collect()

```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        let mut arities = BTreeMap::new();
same transformations as for predicate_types

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +        let mut num_constraints = BTreeMap::new();
ditto

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    }
```suggestion
    ) -> impl Iterator<Item = LcIndex> {
        lc_vec
            .into_iter()
            .map(|lc| self.new_lc(lc).unwrap())
    }
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +                    let mut trace: String = "".to_string();
```suggestion
                    let mut trace;
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +                                    format!("{} - {unsatisfied_constraint}", &label)
```suggestion
                                    format!("{label} - {unsatisfied_constraint}")
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +                        trace = format!("{} - {unsatisfied_constraint}", label.clone());
```suggestion
                        trace = format!("{label} - {unsatisfied_constraint}");
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    pub fn finalize(&mut self, outline_instance: bool) {
Change `outline_instance` to a field in `ConstraintSystem`, and remove it from finalize. Default it to `false`.

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    pub fn new_input_variable<Func>(&mut self, f: Func) -> crate::utils::Result<Variable>
Inspect the `outline_instances` flag here, and create a new witness variable also, output this variable, and add a constraint which enforces that the new instance variable equals the new witness variable.

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system_ref.rs
> +    // }
Todo fix this and add witness_assignment also

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system_ref.rs
> +    /// TODO: Delete the inner enforce_r1cs_constraint function
```suggestion
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system_ref.rs
> +    pub fn finalize(&self, outline_instances: bool) {
remove outline_instances

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +    pub fn get_lc(&self, lc_index: LcIndex) -> crate::gr1cs::Result<LinearCombination<F>> {
```suggestion
    pub fn get_lc<'a>(&'a self, lc_index: LcIndex) -> crate::gr1cs::Result<&'a LinearCombination<F>> {
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system.rs
> +            .cloned()
remove cloned()
```suggestion
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/constraint_system_ref.rs
> +    // TODO: Implement this function
Fix this todo

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/mod.rs
> +/// Computations are expressed in terms of rank-1 constraint systems (R1CS).
GR1CS

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/mod.rs
> +#[derive(Debug, Clone)]
```suggestion
#[derive(Debug, Clone)]
#[non_exhaustive]
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/mod.rs
> +    /// The  predicate acting on constraints
```suggestion
    /// The type of the predicate enforced by this constraint system.
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/mod.rs
> +                .collect::<Vec<LcIndex>>()
```suggestion
            self.argument_lcs.iter().map(|lc_s| lc_s[i])
                .collect::<Vec<LcIndex>>()
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/mod.rs
> +                .collect::<Vec<LcIndex>>()
Maybe we can name the return type to avoid allocation.

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/polynomial_constraint.rs
> +    pub fn new(arity: usize, terms: Vec<(F, Vec<(usize, usize)>)>) -> Self {
```suggestion
    pub fn new(arity: usize, terms: impl IntoIterator<Item = (F, Vec<(usize, usize)>)>) -> Self {
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/gr1cs/predicate/polynomial_constraint.rs
> +    pub fn evaluate(&self, variables: &[F]) -> bool {
```suggestion
    pub fn is_satisfied(&self, variables: &[F]) -> bool {
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/lib.rs
> +//! A GR1CS instance is eqipped to an R1CS predicate by default. Also, there is
```suggestion
//!a GR1CS instance is equipped with an R1CS predicate by default. Also, there is
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/lib.rs
> +//! a seperate
```suggestion
//! a separate
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/lib.rs
> +//! [enforce_r1cs_constraint](`crate::gr1cs::ConstraintSystemRef::enforce_r1cs_constraint`) function that has the exact API as the [enforce_constraint](https://docs.rs/ark-relations/latest/ark_relati
```suggestion
//! [enforce_r1cs_constraint](`crate::gr1cs::ConstraintSystemRef::enforce_r1cs_constraint`) function that has the same API as the [enforce_constraint](https://docs.rs/ark-relations/latest/ark_relations/r1cs/enum.ConstraintSystemRef.html#method.enforce_constraint) function in
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/lib.rs
> +//! previous versions. Hence, by by replacing [enforce_constraint](https://docs.rs/ark-relations/latest/ark_relations/r1cs/enum.ConstraintSystemRef.html#method.enforce_constraint) with
```suggestion
//! previous versions. Hence, by replacing [enforce_constraint](https://docs.rs/ark-relations/latest/ark_relations/r1cs/enum.ConstraintSystemRef.html#method.enforce_constraint) with
```

2025-01-16 21:53 UTC, Pratyush commented on relations/src/utils/matrix.rs
> +pub fn trans<F: Field>(matrix: &Matrix<F>, num_col: usize) -> Matrix<F> {
```suggestion
pub fn transpose<F: Field>(matrix: &Matrix<F>, num_col: usize) -> Matrix<F> {
```

2025-01-30 19:37 UTC, alireza-shirzad commented on relations/src/gr1cs/constraint_system_ref.rs
> +    // }
Realized that there is no such function in the current version of Arkworks so removed it

2025-01-30 21:33 UTC, alireza-shirzad commented on relations/src/gr1cs/predicate/mod.rs
> +                .collect::<Vec<LcIndex>>()
I was unable to get rid of the allocation here

2025-01-31 16:00 UTC, alireza-shirzad commented on relations/src/gr1cs/constraint_system.rs
> +    pub fn new_input_variable<Func>(&mut self, f: Func) -> crate::utils::Result<Variable>
Although this approach seems more efficient, it introduces some complications:
1- It confuses the users in the front-end: ALL of their variables will be witness variables, while they are working with instance variables.
2- Specifically when dealing with the special varible ONE, We can't replace the variable on the front-end (Because of the afformentioned reason), and to perform the replacement on the backend, needs a linear pass over all the constraints, so no gain in performance

2025-01-31 16:07 UTC, alireza-shirzad commented on relations/src/gr1cs/constraint_system.rs
> +    }
I changed this but in the end we need to collect everything, so probabely no gain?

2025-02-01 00:16 UTC, Pratyush approved these changes

2025-02-01 00:20 UTC, merged

2025-04-02 13:56 UTC, rubdos commented
@Pratyush, @alireza-shirzad

Garuda and Pari is impressive work, and I really appreciate the effort to push the Arkworks ecosystem forward! I have a question about the decision to integrate GR1CS directly into the existing relations library. It seems like this breaks compatibility with much of the existing Arkworks tooling, especially proof systems, which could pose challenges for users and maintainers.

Would it make sense to implement GR1CS as a separate constraint system module instead? That way, the existing R1CS-based ecosystem could remain intact while allowing the new generalized constraint system to evolve independently. A simple `From<>` implementation could serve to convert R1CS constraints (from e.g. the standard library) into GR1CS constraints. I’d love to hear your thoughts on this approach and whether it was considered during development.

I'm also wondering to what extent GR1CS is distinct from CCS (see https://eprint.iacr.org/2023/552, as e.g. used in HyperNova or SuperSpartan).

2025-04-04 21:11 UTC, Pratyush commented
Hi @rubdos !

Thanks for you inquiry! While the new GR1CS interface is indeed a breaking change from the prior version, it shouldn't be much work to migrate from the old interface to the newer one. We wanted to avoid an entirely different interface for GR1CS as the existing constraint libraries (e.g. r1cs-std) wouldn't be compatible with GR1CS, and moreover taking advantage of custom gates for these libraries would not be possible.

With respect to the difference b/w CCS and GR1CS, IMHO it's simply that we found the latter easier to work with; instead of expressing everything as hadamard operations between matrix-vector products, we instead require the user to specify the predicates explicitly, which also allows for incorporating support for lookups in the future.